// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7nV8TNoJm1AYbIEhH9BDDh5ZF5wGP0OI',
    appId: '1:324005805909:web:0bf2a663636f0b7e4679dc',
    messagingSenderId: '324005805909',
    projectId: 'urban-tickets-c05e6',
    authDomain: 'urban-tickets-c05e6.firebaseapp.com',
    storageBucket: 'urban-tickets-c05e6.appspot.com',
    measurementId: 'G-NY4Y25JHJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFyxW6k2Uei6wgksbYRMPczH1OIeUEx58',
    appId: '1:324005805909:android:02a753cc68279bb24679dc',
    messagingSenderId: '324005805909',
    projectId: 'urban-tickets-c05e6',
    storageBucket: 'urban-tickets-c05e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlntS_iNa3CguaudZZmVVhXnuxxPu-aH8',
    appId: '1:324005805909:ios:1e84cf490fe12e444679dc',
    messagingSenderId: '324005805909',
    projectId: 'urban-tickets-c05e6',
    storageBucket: 'urban-tickets-c05e6.appspot.com',
    iosBundleId: 'com.example.iqProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlntS_iNa3CguaudZZmVVhXnuxxPu-aH8',
    appId: '1:324005805909:ios:35e19444df86551b4679dc',
    messagingSenderId: '324005805909',
    projectId: 'urban-tickets-c05e6',
    storageBucket: 'urban-tickets-c05e6.appspot.com',
    iosBundleId: 'com.example.iqProject.RunnerTests',
  );
}
